skip_tags: true
clone_depth: 1
pull_requests:
  do_not_increment_build_number: true

version: '{branch} build {build}'
image: Visual Studio 2013

environment:
  BOOST_ROOT: &boost_root C:\Libraries\boost

init:
  - git --version
  - cmake --version
  - msbuild /version
  - git config --global core.autocrlf true

install:
  - dir
  - .\appveyor.bat
  - dir

build:
  parallel: true
  verbosity: minimal

build_script:
  - dir

test_script:
  - dir %BOOST_ROOT%
